/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  static const String PLUGIN_NAME = 'adbot';
  static const String PLUGIN_VERSION = '4.0.0+40';
  static const String APPLE_PAY = 'assets/apple_pay.json';
  static const String GOOGLE_PAY = 'assets/google_pay.json';
  static const String COVER_LETTER = 'assets/icon/cover_letter.svg';
  static const String DIET_CHART = 'assets/icon/diet_chart.svg';
}
